import org.gradle.api.plugins.JavaPluginExtension

class ApplicationVersion {
   Integer major
   Integer minor
   Integer patch
   Boolean release

   ApplicationVersion(Integer major, Integer minor, Integer patch, Boolean release) {
      this.major = major
      this.minor = minor
      this.patch = patch
      this.release = release
   }

   String getRelease() {
        def date = new Date()
        return this.release ? 'beta' : date.format('yyyyMMddHHmmss')
   }

   String getVersion() {
      return "${major}.${minor}.${patch}"
   }

   String getReleaseVersion() {
      def version = this.getVersion()
      def release = this.getRelease()
      if (release != '') version += "." + release
      return version
   }
}

ext {
    applicationVersion = new ApplicationVersion(1, 2, 0, true)
}

allprojects {
    group = 'org.copperforge.mog'
    version = applicationVersion.getReleaseVersion()

    repositories {
        mavenCentral()
        mavenLocal()
    }
}

subprojects {
    configurations.all {
        // Avoid accidental inclusion of a Log4j provider; route Log4j API to SLF4J instead
        exclude group: 'org.apache.logging.log4j', module: 'log4j-core'
    }

    plugins.withType(JavaPlugin).configureEach {
        JavaPluginExtension javaExt = extensions.getByType(JavaPluginExtension)
        javaExt.sourceCompatibility = JavaVersion.VERSION_21
        javaExt.targetCompatibility = JavaVersion.VERSION_21
        javaExt.toolchain.languageVersion.set(JavaLanguageVersion.of(21))

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }
}
