/*
 * This source file was generated by the Gradle 'init' task
 */
package org.copperforge.mog.reporting;

import org.copperforge.mog.reporting.core.ReportException;
import org.copperforge.mog.reporting.definition.Report;
import org.copperforge.mog.reporting.definition.ReportService;
import org.copperforge.mog.reporting.writer.ReportWriter;
import org.copperforge.mog.reporting.writer.ReportWriterService;
import org.copperforge.mog.reporting.xlsx.XLSXReportWriter;

public class App {

    private App() throws ReportException {
        initialize();
    }

    private void initialize() throws ReportException {
        try {
            // TODO find all builders
            
            new XLSXReportWriter().register();
        } catch (Exception e) {
            throw new ReportException(e);
        }
    }

    public static void main(String[] args) throws Exception {
        App app = new App();
        app.generateReport(args);
    }

    private void generateReport(String args[]) throws ReportException {
        Report definition = ReportService.instance().parse("/reports/ccr/ccr.json");
        ReportWriter builder = ReportWriterService.instance().builder(definition.getType());
        builder.build(definition);
        builder.save("temp.xlsx");
    }
}
